#!/bin/sh

cd /usr/share/fonts/X11/encodings/large
mkfontscale -b -s -l -n -r -p /usr/share/fonts/X11/encodings/large -e . .
cd /usr/share/fonts/X11/encodings/
mkfontscale -b -s -l -n -r -p /usr/share/fonts/X11/encodings -e . -e large .
